### ISSUE TITLE
Consider MapSplitter instead Regex in CEFFieldsParser

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-cef#1]
In https://github.com/Graylog2/graylog-plugin-cef/blob/master/src/main/java/org/graylog/plugins/cef/parser/CEFFieldsParser.java#L19 I would suggest using Guava's `MapSplitter` instead of the regex.

A very quick and dirty jmh run suggests that it might be quite a bit faster (and it's much easier to work with):

```
# Run complete. Total time: 00:01:21

Benchmark                  Mode  Cnt         Score         Error  Units
MyBenchmark.testRegex     thrpt   20  24008829.589 ± 1012285.323  ops/s
MyBenchmark.testSplitter  thrpt   20  25376849.628 ±  320557.044  ops/s
```

``` java
Matcher cefMatcher = HEADER_PATTERN.matcher(cef);
if (!cefMatcher.find()) {
    return;
}
final Map<String, String> m = SPLITTER.split(cefMatcher.group(9));
if (m.size() > 0) {
    // Parse out all fields into a map.
    ImmutableMap.Builder<String, String> fieldsBuilder = new ImmutableMap.Builder<>();
    fieldsBuilder.putAll(m);
}
```

**Comment by kroepke** [comment]
see https://github.com/Graylog2/benchmark-cef-parsing

**Comment by lennartkoopmann** [comment]
If you look at it with execution time metrics (`-bm avgt -tu us`), it does not make a big difference:

    # Run complete. Total time: 00:01:22

    Benchmark                 Mode  Cnt  Score   Error  Units
    MyBenchmark.testRegex     avgt   20  0.052 ± 0.004  us/op
    MyBenchmark.testSplitter  avgt   20  0.050 ± 0.001  us/op

I played around with the `MapSplitter` before implementing the regular expression and found it to be not as reliable with for example CEF `msg` fields that itself have empty `k=v` pairs. (SSH messages tend to do this) It will fail with for example:

    java.lang.IllegalArgumentException: Chunk [14] is not a valid entry

I'd vote for keeping it as the regex for now until we run into performance issues.

**Comment by lennartkoopmann** [comment]
For reference, such a message would be:

    dvc=ip-172-30-2-212 msg=Aug 21 19:08:08 ip-172-30-2-212 sshd[28327]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=116.31.116.17  user=root

**Comment by lennartkoopmann** [comment]
Closing this for now.

**Comment by kroepke** [comment]
Fair enough, yes :+1:
