### ISSUE TITLE
Plugin does not fully comply with CEF standard

### ISSUE THREAD

**Issue by omercnet** [Graylog2/graylog-plugin-cef#11]
Hello,

I've been trying to use this plugin with several products but they all got rejected, perhaps this plugin was written for an older revision of CEF?

According to [revision v23 of CEF](https://www.protect724.hpe.com/docs/DOC-1072) events coming through syslog should look like 
`Jan 18 11:07:53 host CEF:Version|Device Vendor|Device Product|Device
Version|Device Event Class ID|Name|Severity|[Extension]`

According to the [regex](https://github.com/Graylog2/graylog-plugin-cef/blob/master/src/main/java/org/graylog/plugins/cef/parser/CEFParser.java#L18) and [test](https://github.com/Graylog2/graylog-plugin-cef/blob/master/src/test/java/org/graylog/plugins/cef/parser/CEFParserTest.java#L17) implemented here the plugin is not expecting a `host` in the syslog message.
`<132>Aug 14 14:26:55 CEF:0|Trend Micro Inc.|OSSEC HIDS|v2.8.3|2502|User.....`

There's also an option to remove the syslog header and use the `start` & `end` CEF fields for timestamp, not sure if it'll be best to check for both or split to to different inputs (or just a checkbox option in the input settings)

Let me know what you think, I'll be happy to write the fix

**Comment by omercnet** [comment]
sorry the mess, trying to avoid multiple issues in a single commit

**Comment by lennartkoopmann** [comment]
Thanks! I'll be looking into this soon.

**Comment by omercnet** [comment]
@lennartkoopmann ?

**Comment by lennartkoopmann** [comment]
This can be solved using processing pipeline steps since the v1.2.0 release of the CEF plugin. See: https://github.com/Graylog2/graylog-plugin-cef/blob/master/README.md#usage
