### ISSUE TITLE
Use `start` or `end` field as timestamp?

### ISSUE THREAD

**Issue by omercnet** [Graylog2/graylog-plugin-cef#16]
Some products will not use syslog and will just send out CEF messages (see #11)
In that case, the producer will (hopefully) send a `start` and `end` fields to indicate the start/end time of the reported event, in most cases they will be the same value but in some cases (like indications of malicious sessions or file downloads) this will be used to indicate the duration of the event.

In that case, I'm not sure if we should use `start` or `end` as the event timestamp. I'm leaning more towards `end` because that will actually be the time the log will be sent

what do you guys think?

**Comment by lennartkoopmann** [comment]
This can be solved using processing pipeline steps since the v1.2.0 release of the CEF plugin. See: https://github.com/Graylog2/graylog-plugin-cef/blob/master/README.md#usage

Parse out the timestamp manually and set the message timestamp using the `set_field()` function.
