### ISSUE TITLE
Don't hardcode using local timezone

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-cef#2]
In https://github.com/Graylog2/graylog-plugin-cef/blob/f98fbbe7c1b9d77e5238a4410b7e9c1ed78ef413/src/main/java/org/graylog/plugins/cef/parser/CEFParser.java#L29-L32 I would not default to using the local timezone.

Instead I would be better to allow configuring the timezone in the `CEFCodec` and then passing it to the parser.
That way users would have more control over it, I've recently seen pretty whacky setups and wouldn't rely on server timezones to be set correctly or sanely.

`DateTimeZone::forID` should be all that's necessary to convert a string to a tz (something like `-0700` or `CET`). Just keep in mind that `forID` expects uppercase, so we might want to convert user input to uppercase for convenience.
Compare https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/master/src/main/java/org/graylog/plugins/pipelineprocessor/functions/dates/TimezoneAwareFunction.java#L36

**Comment by lennartkoopmann** [comment]
Thanks! :)
