### ISSUE TITLE
make the input available with kafka/rabbitmq

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog-plugin-cef#3]
if you do not have the ability to connect from the ossec server to your graylog one possible solution is to use a queue.

on the ossec server, you need to use a forwarder that pushes it to the queue (like logstash) but graylog should be able to read and work with this.

**Comment by lennartkoopmann** [comment]
@jalogisch Do you have a Kafka setup running that you could test this on? Implementing the Kafka Transport would be easy.

**Comment by jalogisch** [comment]
comments in https://github.com/Graylog2/graylog-plugin-cef/pull/5 for kafka

**Comment by bernd** [comment]
Kafka and AMQP inputs have been added in 4c33e53355842953011169995539140361e98a97.
